---
name: CI with Maven
on: 
  push: 
    branches:
      - master
      - main
jobs: 
  build:
    name: "maven"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: maven build
        run: mvn package 
